### ISSUE TITLE
Application keeps hanging on "Loading..."

### ISSUE THREAD

**Issue by SgtBlade** [kolinger/rd-usb#25] opened 2022-02-09 13:19 UTC
I've tried 1.13 and 1.14 Beta but both are stuck on the "Loading...". 
I tried using both the installer and the lightweight version.

The 127.0.0.1:5000 gives Error 500: 
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

I'm on Windows 11 so it might not be compatible yet? Are there any log files I can check?

Console of the lightweight version gives this error:
  ```
  File "C:\Users\******\AppData\Local\Temp\_MEI217802\webapp\templates\layout.html", line 12, in top-level template code
    <link href="{{ url_for('static', filename='css/themes/' + theme + '.bootstrap.min.css') }}" rel="stylesheet" />
jinja2.exceptions.UndefinedError: 'theme' is undefined
2022-02-09 14:18:35,766 - INFO - 127.0.0.1 - - [09/Feb/2022 14:18:35] "←[35m←[1mGET / HTTP/1.1←[0m" 500 -
2022-02-09 14:18:36,286 - ERROR - Exception on / [GET]
Traceback (most recent call last):
```

**Comment by kolinger** [comment] 2022-02-09 13:30
Not Windows 11 related. This was bug affecting all new installations since 1.13.0 on all systems.

Fixed in 1.14.1 - available [here](https://github.com/kolinger/rd-usb/releases).

Please let me know if fix works for you too.

**Comment by SgtBlade** [comment] 2022-02-09 14:49
Jup, that fixed it.

There is another minor bug I found when moving the window to my second monitor:
![image](https://user-images.githubusercontent.com/23322965/153225258-28ab45b2-ff9d-4d66-8eae-685c5d88d581.png)

Though this is something minor as it works perfectly well on my main monitor

**Comment by kolinger** [comment] 2022-02-09 15:12
Window in a window? Very strange. What happens if you click on COM4 or some navigation item? When does this happen exactly? If you move opened window from one to another screen or does this happen on opening of application? I can't reproduce your result.

**Comment by kolinger** [comment] 2022-02-09 15:40
Looks like rendering issues. Perhaps related to accelerated rendering via GPU. You can try to disable GPU rendering as workaround. Modify your shortcut to rd-usb by appending "--disable-gpu". You need new version for this - 1.15.0 - available [here](https://github.com/kolinger/rd-usb/releases).

Like this:
![Screenshot_1](https://user-images.githubusercontent.com/1590930/153234802-4676c998-f813-48b5-b3f1-ad204d231b56.png)

**Comment by SgtBlade** [comment] 2022-02-09 15:44
Disabling the GPU fixed it, thanks!

**Closed** 2022-02-09 15:48 UTC
